### ISSUE TITLE
Update to remove hacktober fest and market as a general tool

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCommunity/your-first-julia-pr#3] opened 2021-08-02 00:50 UTC

**Comment by SaschaMann** [comment] 2021-10-06 22:09
Other than updating copy, you'd only have to change https://github.com/JuliaCommunity/your-first-julia-pr/blob/14d991852c7718d452e7b72d59ff54b28c0546f7/main.go#L64 to include whatever label people use for good first PRs (`good-first-issue`?)

**Comment by SaschaMann** [comment] 2022-10-11 17:47
Duplicate of #8

**Closed as not planned** 2022-10-11 17:47 UTC
Labels: enhancement
